### Create notes in DB, data coming from Frontend
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title" : "false  note",
    "status" : false
}

### Get data from database
GET http://localhost:8080/notes/

### Get data from database based on path params
GET http://localhost:8080/notes?status=false

### Update in database
PUT http://localhost:8080/notes/
Content-Type: application/json

{ "title" : "first  note changing status",
  "status" : true,
  "id": 1
}

### Delete in database
DELETE http://localhost:8080/notes/2



### Auth Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email" : "ankitbourasi0@gmail.com",
  "password" : "123"
}

### Auth Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "ankitbourasi0@gmail.com",
  "password" : "123"
}