### GET request to example server
GET http://localhost:8080/ping

###
GET http://localhost:8080/me/49

###
GET http://localhost:8080/me/49/58

###
POST http://localhost:8080/me
Content-Type: application/json

{
    "email": "ankitbourasi0@gmail.com",
    "password": "123"
}

### Replace Entire Object
POST http://localhost:8080/me/id
Content-Type: application/json

{
  "email": "",
  "password": "123"
}

###
PUT http://localhost:8080/me
Content-Type: application/json

{
  "email": "",
  "password": "123"
}

### Replace Some Part of the Object
PATCH http://localhost:8080/me
Content-Type: application/json

{
  "email": "",
  "password": "123"
}

###
DELETE http://localhost:8080/me/24


###
GET http://localhost:8080/notes
###
POST http://localhost:8080/notes

